title: Blue Horizons Partners
description: >-
  Blue Horizons Partners official website.
baseurl: ""
url: "https://blue-horizons-partners.github.io"

logo: "https://github.com/Blue-Horizons-Partners.png"

contact:
  email: "privacy@blue-horizons-partners.com"
  address: "Blue Horizons Partners, United States"

theme: minima

minima:
  skin: classic
  header_pages:
    - about.md

plugins:
  - jekyll-feed
