title: Blue Horizons Partners
email: "contact@blue-horizons-partners.com"
description: >-
  Blue Horizons Partners official website.
baseurl: ""
url: "https://blue-horizons-partners.github.io"

logo: "/assets/images/blue-horizons-logo.jpg"
minimal_mistakes_skin: default

contact:
  email: "contact@blue-horizons-partners.com"
  address: "Blue Horizons Partners"

theme: minimal-mistakes-jekyll

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/company/blue-horizons-partners-1"

plugins:
  - jekyll-feed
  - jekyll-include-cache
