title: Blue Horizons Partners
email: "contact@blue-horizons-partners.com"
description: >-
  Blue Horizons Partners official website.
baseurl: ""
url: "https://blue-horizons-partners.github.io"

logo: "https://github.com/Blue-Horizons-Partners.png"

contact:
  email: "contact@blue-horizons-partners.com"
  address: "Blue Horizons Partners"

theme: minima

minima:
  skin: classic
  header_pages:
    - about.md
  social_links:
    linkedin: "https://www.linkedin.com/company/blue-horizons-partners-1"

plugins:
  - jekyll-feed
